In [1]:
import tensorflow as tf

In [2]:
print("TensorFlow",tf.__version__)

TensorFlow 2.16.1


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0 

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/Users/shivanimishra/anaconda3/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2024-05-28 19:38:24.477094: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3
2024-05-28 19:38:24.477382: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-05-28 19:38:24.477402: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-05-28 19:38:24.477489: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-05-28 19:38:24.477603: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhos

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.288652  ,  0.26124313,  0.82044363, -0.10977066,  0.82596946,
         0.45162022,  0.07158001,  0.29973266, -0.3278734 ,  0.16308594]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.05595094, 0.09696696, 0.16962174, 0.06691054, 0.17056163,
        0.11730149, 0.08021473, 0.10077194, 0.05379894, 0.08790118]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.1430078

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2024-05-28 19:40:01.722713: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8560 - loss: 0.4921
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9552 - loss: 0.1537
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9663 - loss: 0.1148
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9724 - loss: 0.0904
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9745 - loss: 0.0799


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9739 - loss: 0.0833


[0.08328992128372192, 0.9739000201225281]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.93734484e-08, 7.62871633e-09, 2.14053671e-06, 8.36446357e-04,
        1.11074509e-11, 3.37431828e-07, 4.20205041e-15, 9.99148607e-01,
        4.13115600e-07, 1.19345050e-05],
       [2.92886781e-08, 4.80737392e-04, 9.99508739e-01, 6.09541132e-07,
        1.57360985e-14, 1.56476904e-06, 5.70467955e-06, 5.67702115e-14,
        2.55880286e-06, 2.12520630e-15],
       [8.98011649e-07, 9.97966528e-01, 1.85927245e-04, 2.87295934e-05,
        1.16949246e-04, 2.48533142e-05, 7.93934032e-06, 1.39846909e-03,
        2.68096541e-04, 1.55484838e-06],
       [9.99976039e-01, 2.56175359e-11, 1.20837794e-05, 7.78644619e-07,
        3.84556342e-09, 2.36265214e-06, 7.18287311e-06, 7.32799720e-07,
        1.23733264e-08, 7.21623167e-07],
       [1.13600261e-04, 2.85343776e-10, 1.00862508e-05, 1.05832498e-07,
        9.98236179e-01, 7.47278909e-06, 3.31171963e-04, 1.24897269e-04,
        1.66695736e-05, 1.15970813e-03]], dtype=float32)>